apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rehearsal-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: {{ .Values.ingress.hostFrontend }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: svc-frontend
            port:
              number: 3000

  - host: {{ .Values.ingress.hostBackend }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: svc-backend-python
            port:
              number: 8000
