apiVersion: v1
kind: Service
metadata:
  name: svc-frontend

spec:
  type: ClusterIP
  selector:
    app: frontend

  ports:
  - port: {{ .Values.frontend.port }}
    targetPort: {{ .Values.frontend.port }}