---
apiVersion: v1
kind: Service
metadata:
  name: svc-backend-python

spec:
  type: ClusterIP
  selector:
    app: backend-python

  ports:
  - port: {{ .Values.backend.port }}
    targetPort: {{ .Values.backend.port }}